pool:
  vmImage: 'macOS-10.13'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.1.500' 

- script: |
    dotnet tool install --version "2.1.0" -g Wyam.Tool
    ~/.dotnet/tools/wyam build --update-packages --recipe "Docs" --theme "Samson" --output "$(Build.ArtifactStagingDirectory)/output"
  displayName: 'Generate WYAM Site'
  env:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/output' 
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/output.zip'
  displayName: 'Zip Generated output'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
  condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')))
  displayName: 'Publish Artifact'
